import {getState,save,storeNotice} from './store.js';
import * as landing from './pages/landing.js';
import * as mealsPage from './pages/meals.js';
import * as orders from './pages/orders.js';
import * as planner from './pages/planner.js';
import * as tracker from './pages/tracker.js';
import * as partner from './pages/partner.js';
import * as support from './pages/support.js';
import {esc,empty} from './ui.js';
let route='',menuOpen=false,lastOpener=null,toastTimer=null;
const app=document.querySelector('#app');
function current(){const hash=location.hash||'#/';const [path,query='']=hash.slice(1).split('?');return {path:path||'/',query}}
function nav(path,label){return `<a href="#${path}" ${route===path?'aria-current="page"':''}>${label}</a>`}
function header(){const partnerMode=route.startsWith('/partner'),landingMode=route==='/';return `<div class="demo-strip">Interactive demo · No real orders or payments · <a href="#/about-demo">About this demo</a> · <button class="reset-link" data-action="reset-demo">Reset demo</button></div><header class="site-header"><div class="header-inner"><a class="brand" href="#/" aria-label="KEDRYN home">KEDRYN</a><button class="menu-toggle secondary" data-action="menu-toggle" aria-expanded="${menuOpen}" aria-controls="main-nav">${menuOpen?'Close menu':'Menu'}</button><nav id="main-nav" class="nav ${menuOpen?'open':''}" aria-label="Main navigation">${partnerMode?`${nav('/partner','Overview')}${nav('/partner/referrals','Referrals')}${nav('/partner/payouts','Payouts')}${nav('/partner/assets','Marketing assets')}${nav('/home','Switch to customer')}`:landingMode?`${nav('/meals','Meals')}${nav('/planner','Meal planner')}${nav('/family','For families')}${nav('/partner','For gyms')}${nav('/wellness','More')}${nav('/cart',`Cart (${getState().cart.length})`)}`:`${nav('/meals','Meals')}${nav('/planner','Meal planner')}${nav('/tracker','Food log')}${nav('/plans','Saved plans')}${nav('/cart',`Cart (${getState().cart.length})`)}<details class="customer-menu"><summary>Customer menu</summary><div class="customer-menu-panel">${nav('/home','Customer home')}${nav('/orders','Orders')}${nav('/preferences','Preferences')}${nav('/partner','Gym partner demo')}</div></details>`}</nav><div class="header-actions"><a class="button secondary" href="#/home">Explore as customer</a><a class="button" href="#/partner">Explore as gym partner</a></div></div></header>`}
function footer(){return `<footer class="footer"><div class="footer-inner"><div><div class="brand" style="color:white">KEDRYN</div><p>Familiar food. Clearer choices.</p><small style="color:white">Interactive demo · No real orders or payments</small></div><div>${[['Meals','/meals'],['Meal planner','/planner'],['Ingredient labels','/knowledge/labels'],['Partner demo','/partner'],['Demo information','/about-demo']].map(([l,h])=>`<a href="#${h}">${l}</a>`).join('')}<button data-action="reset-demo">Reset demo</button></div></div></footer>`}
function page(){const {path}=current();if(path==='/')return landing.landing();if(path==='/home')return support.home();if(path==='/meals')return mealsPage.catalog();if(path.startsWith('/meals/'))return mealsPage.detailPage(path.split('/')[2]);if(path==='/cart')return orders.cart();if(path==='/checkout')return orders.checkout();if(path==='/orders')return orders.orders();if(path.startsWith('/orders/'))return orders.orderDetail(path.split('/')[2]);if(path==='/planner')return planner.planner();if(path==='/plans')return planner.savedPlans();if(path==='/tracker')return tracker.tracker();if(path==='/preferences')return support.preferences();if(path==='/family')return support.family();if(path==='/knowledge/labels')return support.labels();if(path==='/wellness')return support.wellness();if(path.startsWith('/partner'))return partner.partner(path.slice(1));if(path==='/about-demo')return support.demo();return empty('Page not found','The address is not part of this demo.','#/','Go home')}
export function render(){const active=document.activeElement?.getAttribute('data-action'),y=window.scrollY;app.innerHTML=`${header()}<main id="main" class="shell" tabindex="-1">${storeNotice()?`<div class="notice error">${esc(storeNotice())}</div>`:''}${page()}</main>${footer()}`;if(active){const newActive=app.querySelector(`[data-action="${CSS.escape(active)}"]`);newActive?.focus({preventScroll:true})}app.querySelectorAll('.local-photo').forEach(img=>{const fallback=()=>{img.hidden=true;img.parentElement.classList.add('photo-failed');img.parentElement.querySelector('.meal-photo-fallback')?.setAttribute('aria-hidden','false')};img.addEventListener('error',fallback,{once:true});if(img.complete&&img.naturalWidth===0)fallback()});window.scrollTo(0,y)}
function hideToast(){const toast=document.querySelector('#cart-toast');if(toast)toast.hidden=true;if(toastTimer){clearTimeout(toastTimer);toastTimer=null}}
function announce(msg){document.querySelector('#live').textContent=msg;if(msg==='Meal added to cart.'){const toast=document.querySelector('#cart-toast');toast.hidden=false;if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(hideToast,6000)}}
document.querySelector('#toast-close').addEventListener('click',hideToast);document.querySelector('#cart-toast a').addEventListener('click',hideToast);
function openDialog(markup){document.querySelector('dialog')?.remove();lastOpener=document.activeElement;document.body.insertAdjacentHTML('beforeend',markup);const d=document.body.querySelector('dialog');d.addEventListener('close',()=>{if(d.id==='photo-dialog')tracker.cleanup();d.remove();lastOpener?.focus()},{once:true});d.showModal()}
function routeChange(){hideToast();const next=current();route=next.path;menuOpen=false;document.querySelector('dialog')?.close();if(route==='/meals')mealsPage.initMeals(next.query);if(route==='/tracker')tracker.initTracker(next.query);if(route==='/planner')planner.initPlanner();if(route.startsWith('/partner'))partner.load();render();window.scrollTo(0,0);document.querySelector('#main')?.focus({preventScroll:true})}
window.addEventListener('hashchange',routeChange);window.addEventListener('kedryn:render',render);window.addEventListener('kedryn:external',render);
app.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;if(action==='menu-toggle'){menuOpen=!menuOpen;render();return}if(action==='close-dialog'){document.querySelector('dialog')?.close();tracker.cleanup();return}await landing.handle(action,el,render,announce);await mealsPage.handle(action,el,render,announce);await orders.handle(action,el,render,announce,openDialog);await planner.handle(action,el,render,announce,openDialog);await tracker.handle(action,el,render,announce,openDialog);await partner.handle(action,el,render,announce,openDialog);await support.handle(action,el,render,announce,openDialog,tracker.cleanup)});
document.body.addEventListener('click',async e=>{if(!e.target.closest('dialog'))return;const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;if(action==='close-dialog'){document.querySelector('dialog')?.close();tracker.cleanup();return}await orders.handle(action,el,render,announce,openDialog);await planner.handle(action,el,render,announce,openDialog);await tracker.handle(action,el,render,announce,openDialog);await support.handle(action,el,render,announce,openDialog,tracker.cleanup)});
app.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='checkout-form')orders.submitCheckout(render,announce);if(e.target.id==='preferences-form')support.savePreferences(announce)});
app.addEventListener('change',async e=>{const el=e.target,name=el.name,value=el.value;if(name==='photo-upload'){tracker.fileChange(el.files[0],render,announce,openDialog);return}landing.change(name,value,render);mealsPage.change(name,value,render);orders.change(name,value,el,render);planner.change(name,value,el,render);tracker.change(name,value,render);partner.change(name,value);support.change(name,value,render)});
routeChange();

if ('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost' || location.hostname === '127.0.0.1')) {
  window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(error => console.warn('KEDRYN offline support could not be enabled:', error)));
}
