import {meals,mealList,allergenChoices,available,portions} from '../data/catalog.js';
import {getState,save} from '../store.js';
import {getMeals,addCartLine} from '../services/mock-api.js';
import {mealCard,image,nutrition,esc,empty,alert,dateSelect,slotSelect,toggleFav} from '../ui.js';
import {DATES} from '../domain/dates.js';
import {rupees,portionPrice,portionNutrition} from '../domain/math.js';
let filters={search:'',window:'',diet:'vegetarian',allergens:[],ingredients:[],minPrice:0,maxPrice:99999,minProtein:0,maxCalories:99999,availableOnly:false,date:DATES[0],sort:'recommended',favourites:false};let result=null,loading=false,filterOpen=false,detail={date:DATES[0],slot:'lunch',portionId:'standard',quantity:1};
export function initMeals(query){const q=new URLSearchParams(query);filters={...filters,search:q.get('search')||'',window:q.get('window')||'',favourites:q.get('favourites')==='1',date:q.get('date')||DATES[0]};if(q.get('ref')?.toUpperCase()==='KEDRYN-FORGE')save(s=>s.referral='KEDRYN-FORGE');return load()}
export async function load(){loading=true;result=await getMeals(filters);loading=false;window.dispatchEvent(new Event('kedryn:render'))}
export function catalog(){
 const ids=result?.ok?result.data.mealIds:[];
 const categories=['breakfast','lunch','snacks','dinner'].map(key=>({key,label:key==='snacks'?'Snacks':key[0].toUpperCase()+key.slice(1),ids:ids.filter(id=>(filters.window?[filters.window]:meals[id].mealWindows)[0]===key)})).filter(group=>group.ids.length);
 const menuRows=group=>group.ids.map(id=>{
  const m=meals[id],can=available(m,filters.date,filters.window||m.mealWindows[0]),saved=getState().favourites.includes(id);
  return `<article class="menu-row"><div class="menu-row-copy"><div class="menu-row-tags"><span class="food-mark" aria-label="Vegetarian">▣</span>${m.vegan?'<span class="menu-vegan">Vegan</span>':''}<button class="menu-favourite" data-action="favourite" data-id="${id}" aria-label="${saved?'Remove':'Add'} ${esc(m.name)} ${saved?'from':'to'} favourites" aria-pressed="${saved}">${saved?'♥':'♡'}</button></div><h3><a href="#/meals/${id}">${esc(m.name)}</a></h3><strong class="menu-price">${rupees(m.basePricePaise)}</strong><p>${esc(m.description)}</p><small>${m.nutritionPerStandard.kcal} kcal · ${m.nutritionPerStandard.p}g protein estimate · ${m.standardServingGrams}g</small>${can?'':'<small class="menu-unavailable">Unavailable for this delivery selection</small>'}</div><div class="menu-row-action"><a class="menu-thumb-link" href="#/meals/${id}" aria-label="View ${esc(m.name)} details">${image(m)}</a><button class="menu-add" data-action="quick-add" data-id="${id}" data-date="${filters.date}" data-slot="${filters.window||m.mealWindows[0]}" ${can?'':'disabled'}>${can?'Add':'Unavailable'}</button></div></article>`;
 }).join('');
 const content=loading?'<p role="status">Loading menu…</p>':!result?.ok?`${alert(result?.error.message||'Could not load the menu.','error')}<button data-action="retry-catalog">Retry</button>`:result.data.count?`<div class="menu-list">${categories.map(group=>`<section class="menu-category" id="menu-${group.key}"><div class="menu-category-heading"><h2>${group.label}</h2><span>${group.ids.length} ${group.ids.length===1?'item':'items'}</span></div>${menuRows(group)}</section>`).join('')}</div><details class="menu-index"><summary><span class="menu-index-icon" aria-hidden="true">☰</span><span>Menu</span></summary><div class="menu-index-panel"><strong>Browse categories</strong>${categories.map(group=>`<button type="button" data-action="menu-category" data-category="${group.key}"><span>${group.label}</span><span>${group.ids.length}</span></button>`).join('')}</div></details>`:empty('No meals available','There are no meals to show for this selection.');
 return `<section class="page-intro"><div class="eyebrow">Explore the menu</div><h1>Meals for your day.</h1><p>Browse familiar prepared meals with ingredient details and nutrition estimates.</p></section><div class="catalog-count" role="status">${result?.ok?`${result.data.count} ${result.data.count===1?'meal':'meals'}`:loading?'Loading menu…':'Menu'}</div><div class="catalog-results catalog-results-menu">${content}</div>`;
}
export function detailPage(id){const m=meals[id];if(!m)return empty('Meal not found','Return to the menu to choose another meal.','#/meals','Explore meals');if(!m.mealWindows.includes(detail.slot))detail.slot=m.mealWindows[0];if(!m.portionIds.includes(detail.portionId))detail.portionId='standard';const can=available(m,detail.date,detail.slot);const n=portionNutrition(id,detail.portionId,detail.quantity),price=portionPrice(id,detail.portionId)*detail.quantity;return `<a href="#/meals">← All meals</a><div class="hero" style="min-height:0;margin-top:25px"><div>${image(m)}</div><div><div class="eyebrow">${m.mealWindows.join(' · ')}</div><h1>${esc(m.name)}</h1><p>${esc(m.description)}</p><p>${m.vegan?'Vegan':'Vegetarian'} · Standard serving ${m.standardServingGrams}g</p><h2>${rupees(price)}</h2><p>Illustrative nutrition estimate for selected portion and quantity.</p>${nutrition(n)}<div class="form-grid"><label class="field">Delivery date ${dateSelect('detail-date',detail.date)}</label><label class="field">Meal window ${slotSelect('detail-slot',detail.slot,m)}</label><label class="field">Portion<select name="detail-portion">${m.portionIds.map(p=>`<option value="${p}" ${p===detail.portionId?'selected':''}>${portions[p].label}</option>`).join('')}</select></label><label class="field">Quantity<input type="number" min="1" max="10" name="detail-qty" value="${detail.quantity}"></label></div><div class="actions"><button data-action="detail-add" data-id="${id}" ${can?'':'disabled'}>Add to cart</button><button class="secondary" data-action="favourite" data-id="${id}" aria-pressed="${getState().favourites.includes(id)}">${getState().favourites.includes(id)?'♥ Saved':'♡ Favourite'}</button></div>${can?'':alert('Unavailable for this date and meal window. Choose another option.','error')}</div></div><section class="section"><h2>What is in this demo recipe</h2><p>${esc(m.ingredientIds.join(', '))}.</p><p><strong>Declared allergens:</strong> ${m.declaredAllergenIds.length?esc(m.declaredAllergenIds.join(', ')):'None declared in fixture'}.</p><p>${esc(m.preparationNotes)}</p>${alert('Ingredient exclusions use stated demo recipes. Cross-contact safety is not established.')}</section>`}
export function handle(action,el,rerender,announce){if(action==='menu-category'){document.querySelector('.menu-index')?.removeAttribute('open');document.getElementById(`menu-${el.dataset.category}`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}if(action==='favourite'){toggleFav(el.dataset.id);rerender()}if(action==='filter-toggle'){filterOpen=!filterOpen;rerender()}if(action==='apply-filters'){const root=document.querySelector('#filters');const v=n=>root.querySelector(`[name="${n}"]`)?.value;filters={...filters,search:document.querySelector('#meal-search')?.value||'',window:v('window'),diet:v('diet'),allergens:[...root.querySelectorAll('[name="allergen"]:checked')].map(x=>x.value),ingredients:v('ingredients').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),minPrice:+v('minPrice')||0,maxPrice:+v('maxPrice')||99999,minProtein:+v('minProtein')||0,maxCalories:+v('maxCalories')||99999,availableOnly:root.querySelector('[name="availableOnly"]').checked,date:v('date'),sort:v('sort')};load()}if(action==='clear-filters'){filters={search:'',window:'',diet:'vegetarian',allergens:[],ingredients:[],minPrice:0,maxPrice:99999,minProtein:0,maxCalories:99999,availableOnly:false,date:DATES[0],sort:'recommended',favourites:false};load()}if(action==='retry-catalog')load();if(action==='quick-add'){const r=addCartLine({mealId:el.dataset.id,portionId:'standard',quantity:1,deliveryDate:el.dataset.date,deliveryWindowId:el.dataset.slot});announce(r.ok?'Meal added to cart.':r.error.message);rerender()}if(action==='detail-add'){const r=addCartLine({mealId:el.dataset.id,portionId:detail.portionId,quantity:detail.quantity,deliveryDate:detail.date,deliveryWindowId:detail.slot});announce(r.ok?'Meal added to cart.':r.error.message);rerender()}}
export function change(name,value,rerender){if(name==='detail-date')detail.date=value;if(name==='detail-slot')detail.slot=value;if(name==='detail-portion')detail.portionId=value;if(name==='detail-qty')detail.quantity=Math.max(1,Math.min(10,+value||1));if(name.startsWith('detail-'))rerender()}
