import {getState} from '../store.js';
import {getPartnerMetrics,exportPartnerCsv} from '../services/mock-api.js';
import {rupees} from '../domain/math.js';
import {dateLabel} from '../domain/dates.js';
import {esc,alert,empty} from '../ui.js';
let from='2026-09-26',to='2026-10-02',metrics=null,chart='sales',busy=false,copyFallback=false,period='7';
export async function load(){busy=true;const key=`${from}|${to}`;const r=await getPartnerMetrics({from,to});if(key===`${from}|${to}`)metrics=r;busy=false;window.dispatchEvent(new Event('kedryn:render'))}
const link=()=>`${location.origin}${location.pathname}${location.search}#/meals?ref=KEDRYN-FORGE`;
const money=p=>rupees(p||0);
function filters(){return `<div class="toolbar"><label class="field">Period<select name="partner-period"><option value="7" ${period==='7'?'selected':''}>Last 7 demo days</option><option value="30" ${period==='30'?'selected':''}>Last 30 demo days</option><option value="all" ${period==='all'?'selected':''}>All time</option><option value="custom" ${period==='custom'?'selected':''}>Custom</option></select></label>${period==='custom'?`<label class="field">From<input type="date" name="partner-from" value="${from}"></label><label class="field">To<input type="date" name="partner-to" value="${to}"></label><button data-action="partner-apply">Apply dates</button>`:''}<button class="secondary" data-action="partner-csv">Download current CSV</button></div>`}
function metricCards(d){return `<div class="metrics">${[['Referred customers',d.metrics.customers],['Attributed orders',d.metrics.orders],['Eligible sales',money(d.metrics.eligiblePaise)],['Estimated commission',money(d.metrics.commissionPaise)]].map(([l,v])=>`<div class="metric"><small>${l}</small><strong>${v}</strong></div>`).join('')}</div><p class="meta">Period: ${dateLabel(from)}–${dateLabel(to)}. Customers are distinct aliases with non-cancelled attributed orders; sales exclude delivery and tax.</p><h2>All-time balances</h2><div class="metrics three">${[['Pending',d.balances.pending],['Approved',d.balances.approved],['Paid',d.balances.paid]].map(([l,v])=>`<div class="metric"><small>${l}</small><strong>${money(v)}</strong></div>`).join('')}</div>`}
function rows(d){return `<div class="table-wrap desktop-table"><table><caption>Filtered attributed orders, including void rows</caption><thead><tr><th>Order</th><th>Date</th><th>Customer</th><th>Status</th><th>Merchandise</th><th>Eligible</th><th>Commission</th></tr></thead><tbody>${d.rows.map(r=>`<tr><td>${esc(r.order_id)}</td><td>${esc(r.order_date_ist)}</td><td>${esc(r.customer_alias)}</td><td>${esc(r.commission_status)}</td><td>${money(r.merchandise_inr*100)}</td><td>${money(r.eligible_inr*100)}</td><td>${money(r.commission_inr*100)}</td></tr>`).join('')}</tbody></table></div><div class="partner-cards">${d.rows.map(r=>`<article class="line"><h3>${esc(r.order_id)}</h3><p>${dateLabel(r.order_date_ist)} · ${esc(r.customer_alias)}</p><p>Order: ${esc(r.order_status)} · Commission: ${esc(r.commission_status)}</p><p>Merchandise ${money(r.merchandise_inr*100)} · Eligible ${money(r.eligible_inr*100)} · Commission ${money(r.commission_inr*100)}</p></article>`).join('')}</div>`}
function chartDates(){const start=new Date(`${from}T12:00:00Z`),end=new Date(`${to}T12:00:00Z`);const span=Math.round((end-start)/86400000);if(!Number.isFinite(span)||span<0||span>31)return null;return Array.from({length:span+1},(_,i)=>new Date(start.getTime()+i*86400000).toISOString().slice(0,10))}
function dailySeries(d){const dates=chartDates()||[...new Set(d.rows.map(r=>r.order_date_ist))].sort();return dates.map(date=>{const rows=d.rows.filter(r=>r.order_date_ist===date&&r.commission_status!=='void');return {date,sales:rows.reduce((a,r)=>a+Math.round(r.eligible_inr*100),0),commission:rows.reduce((a,r)=>a+Math.round(r.commission_inr*100),0)}})}
function chartView(d){const series=dailySeries(d),key=chart==='sales'?'sales':'commission',max=Math.max(1,...series.map(x=>x[key]));return `<div class="between partner-chart-heading"><h2>Daily ${chart==='sales'?'eligible sales':'commission'}</h2><button class="secondary" data-action="partner-chart">Show ${chart==='sales'?'commission':'sales'}</button></div>${series.length?`<div class="partner-chart-scroll"><div class="partner-chart" role="img" aria-label="Daily ${chart==='sales'?'eligible sales':'commission'} from ${dateLabel(from)} to ${dateLabel(to)}. Exact values are listed in the table below.">${series.map(r=>`<div class="partner-bar-column"><strong class="partner-bar-value">${r[key]?money(r[key]):'₹0'}</strong><div class="partner-bar-track"><div class="partner-bar" style="height:${r[key]?Math.max(4,Math.round(r[key]/max*168)):0}px" title="${dateLabel(r.date)}: ${money(r[key])}"></div></div><span class="partner-bar-date">${r.date.slice(5)}</span></div>`).join('')}</div></div><div class="table-wrap"><table class="daily-chart-table"><caption>Daily ${chart==='sales'?'eligible sales':'commission'} values for the selected period</caption><thead><tr><th>Date</th><th>Eligible sales</th><th>Commission</th></tr></thead><tbody>${series.map(r=>`<tr><th>${dateLabel(r.date)}</th><td>${money(r.sales)}</td><td>${money(r.commission)}</td></tr>`).join('')}</tbody></table></div>`:empty('No chart data in this period','Choose another date range to see commercial activity.')}`}

export function partner(route){const d=metrics?.ok?metrics.data:null;const intro=`<div class="page-intro"><div class="eyebrow">Forge Fitness — Demo · Rohan Demo</div><h1>Gym partner ${route==='partner'?'overview':route.split('/')[1]}.</h1><p>Fictional commercial activity. Referrals and commissions use the same local orders as the customer demo.</p></div><nav class="toolbar" aria-label="Partner sections"><a class="button secondary" href="#/partner">Overview</a><a class="button secondary" href="#/partner/referrals">Referrals</a><a class="button secondary" href="#/partner/payouts">Payouts</a><a class="button secondary" href="#/partner/assets">Marketing assets</a></nav>`;if(route==='partner/assets')return intro+assets();return intro+filters()+(busy?'<p role="status">Loading partner figures…</p>':!metrics?.ok?alert(metrics?.error.message||'Loading…','error'):route==='partner/payouts'?payouts(d):route==='partner/referrals'?`<section class="section"><h2>Attributed orders</h2>${rows(d)}</section>`:`${metricCards(d)}<section class="section panel">${chartView(d)}</section><section class="section"><h2>Recent attributed orders</h2>${rows(d)}</section><section class="section panel"><h2>Commission rule</h2><p>Illustrative 10% of merchandise after discounts, rounded once per order. Delivery and tax are excluded. Cancelled orders are void; fully delivered orders become approved. Referral codes do not discount customer orders.</p></section>`)}
function payouts(d){return `${metricCards(d)}<section class="section panel"><h2>Preview approved payout</h2><p>${money(d.balances.approved)} is approved in this fictional demo. Previewing creates no payment or balance change.</p><button data-action="preview-payout">Preview payout</button></section><section class="section"><h2>Fictional payout history</h2>${getState().payouts.map(p=>`<article class="line"><strong>${esc(p.id)}</strong><p>${money(p.amountPaise)} settled · ${dateLabel(p.settledAt.slice(0,10))} · ${esc(p.fictionalReference)}</p></article>`).join('')}</section>`}
function cardSvg(n){const code='KEDRYN-FORGE';return `<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540"><rect width="960" height="540" fill="${n===1?'#542335':'#F9F1E5'}"/><text x="70" y="100" fill="${n===1?'#FCF8F2':'#542335'}" font-size="38" font-family="Georgia">KEDRYN</text><text x="70" y="230" fill="${n===1?'#FCF8F2':'#542335'}" font-size="56" font-family="Georgia">Familiar food.</text><text x="70" y="300" fill="${n===1?'#FCF8F2':'#542335'}" font-size="56" font-family="Georgia">Clearer choices.</text><text x="70" y="400" fill="${n===1?'#FCF8F2':'#542335'}" font-size="28" font-family="Arial">Explore the demo with ${code}</text><text x="70" y="475" fill="${n===1?'#FCF8F2':'#542335'}" font-size="20" font-family="Arial">Interactive demo · No real orders or discounts</text></svg>`}
function assets(){return `<section class="panel"><h2>Your referral link</h2><p class="meta">Generated for this local app. Works in the same browser's demo state.</p><p style="overflow-wrap:anywhere"><code>${esc(link())}</code></p><button data-action="partner-copy">Copy referral link</button>${copyFallback?`<label class="field">Select and copy manually<input readonly value="${esc(link())}" onclick="this.select()"></label>`:''}<h3>Campaign copy</h3><p id="campaign-copy">Explore familiar meals and clearer meal information in the KEDRYN demo. Use our referral code KEDRYN-FORGE to see how gym attribution works. Demo only; no real orders or discounts.</p><div class="actions"><button class="secondary" data-action="copy-campaign">Copy campaign text</button><button class="secondary" data-action="insert-link">Add referral link to text</button></div><h3>Downloadable cards</h3><div class="actions"><button data-action="download-card" data-card="1">Download plum SVG</button><button data-action="download-card" data-card="2">Download cream SVG</button></div></section>`}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export async function handle(action,el,rerender,announce,openDialog){if(action==='partner-apply'){from=document.querySelector('[name="partner-from"]').value;to=document.querySelector('[name="partner-to"]').value;load()}if(action==='partner-chart'){chart=chart==='sales'?'commission':'sales';rerender()}if(action==='partner-csv'){if(!metrics?.ok)return;const x=exportPartnerCsv(metrics.data.rows,from,to);download(x.blob,x.filename)}if(action==='partner-copy'||action==='copy-campaign'){const value=action==='partner-copy'?link():document.querySelector('#campaign-copy')?.textContent;try{await navigator.clipboard.writeText(value);announce('Copied to clipboard.')}catch{copyFallback=true;rerender();announce('Clipboard unavailable. Select the text and copy it manually.')}}if(action==='insert-link'){const p=document.querySelector('#campaign-copy');if(p&&!p.textContent.includes(link()))p.textContent+=` ${link()}`;announce('Referral link added to campaign text.')}if(action==='download-card'){download(new Blob([cardSvg(+el.dataset.card)],{type:'image/svg+xml'}),`kedryn-forge-card-${el.dataset.card}.svg`)}if(action==='preview-payout'){openDialog(`<dialog><h2>Payout preview</h2><p>Approved funds: ${money(metrics.data.balances.approved)}. This preview creates no transfer, payment record or balance change.</p><p>Relevant approved records: ${getState().commissions.filter(x=>x.status==='approved').map(x=>esc(x.id)).join(', ')||'None'}.</p><button data-action="close-dialog">Close</button></dialog>`)}}
export function change(name,value){if(name==='partner-period'){period=value;if(value==='7'){from='2026-09-26';to='2026-10-02'}else if(value==='30'){from='2026-09-03';to='2026-10-02'}else if(value==='all'){from='1900-01-01';to='2026-10-02'}if(value!=='custom')load();else window.dispatchEvent(new Event('kedryn:render'))}}
