import {meals,mealList,available,compatible} from '../data/catalog.js';
import {getState,save,nextId,reset} from '../store.js';
import {DATES,validDelivery} from '../domain/dates.js';
import {portionPrice,portionNutrition,cartTotals,lineSnapshot,commissionFor,addNutrition} from '../domain/math.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const ok=(data,warnings=[])=>({ok:true,data,warnings});const fail=(code,message,fieldErrors={})=>({ok:false,error:{code,message,fieldErrors}});
let failCheckout=false,failCatalog=false;
export const injectCheckoutFailure=()=>{failCheckout=true};export const injectCatalogFailure=()=>{failCatalog=true};
export async function checkServiceability({pin}){await wait(250);if(!/^\d{6}$/.test(pin))return fail('PIN_FORMAT','Enter a valid six-digit PIN code.');return ok({supported:['560001','560038'].includes(pin),windows:['breakfast','lunch','snacks','dinner']})}
export async function getMeals({search='',window='',diet='vegetarian',allergens=[],ingredients=[],minPrice=0,maxPrice=99999,minProtein=0,maxCalories=99999,availableOnly=false,date=DATES[0],sort='recommended',favourites=false}={}){await wait(120);if(failCatalog){failCatalog=false;return fail('CATALOG_LOAD','The simulated catalog request failed. Please retry.')}let ids=mealList.filter(m=>(!search||`${m.name} ${m.ingredientIds.join(' ')}`.toLowerCase().includes(search.toLowerCase()))&&(!window||m.mealWindows.includes(window))&&compatible(m,{diet,allergens,ingredients})&&m.basePricePaise>=minPrice*100&&m.basePricePaise<=maxPrice*100&&m.nutritionPerStandard.p>=minProtein&&m.nutritionPerStandard.kcal<=maxCalories&&(!availableOnly||available(m,date,window||m.mealWindows[0]))&&(!favourites||getState().favourites.includes(m.id)));const sorters={recommended:(a,b)=>a.featuredRank-b.featuredRank,'price-asc':(a,b)=>a.basePricePaise-b.basePricePaise,'price-desc':(a,b)=>b.basePricePaise-a.basePricePaise,'protein-desc':(a,b)=>b.nutritionPerStandard.p-a.nutritionPerStandard.p,'calories-asc':(a,b)=>a.nutritionPerStandard.kcal-b.nutritionPerStandard.kcal};ids.sort((a,b)=>(sorters[sort]||sorters.recommended)(a,b)||a.id.localeCompare(b.id));return ok({mealIds:ids.map(m=>m.id),count:ids.length})}
export async function getMealDetail({mealId,date=DATES[0],window,portionId='standard'}){await wait(100);const meal=meals[mealId];if(!meal)return fail('UNKNOWN_MEAL','Meal not found.');if(!meal.portionIds.includes(portionId))return fail('PORTION','This portion is unavailable.');return ok({meal,available:available(meal,date,window||meal.mealWindows[0]),pricePaise:portionPrice(mealId,portionId),nutrition:portionNutrition(mealId,portionId)})}
export function validateLine(l){const m=meals[l.mealId];return !!m&&m.portionIds.includes(l.portionId)&&Number.isInteger(l.quantity)&&l.quantity>=1&&l.quantity<=10&&validDelivery(l.deliveryDate)&&available(m,l.deliveryDate,l.deliveryWindowId)}
export function addCartLine(line){if(!validateLine(line))return fail('CART_LINE','Choose an available meal, date, window, portion and quantity.');let id;save(s=>{const match=s.cart.find(l=>['mealId','portionId','deliveryDate','deliveryWindowId','householdMemberId','sourcePlanItemId'].every(k=>(l[k]||'')===(line[k]||'')));if(match){match.quantity=Math.min(10,match.quantity+line.quantity);id=match.id}else{id=nextId(s,'cart','CART-');s.cart.push({id,...line})}});return ok({id})}
export function validateCheckout(s,details,referral){const errors={};if(!s.cart.length)errors.cart='Add at least one meal.';if(s.cart.some(l=>!validateLine(l)))errors.cart='Cart contains an unavailable or invalid item.';if(!details.name||details.name.trim().length<2||details.name.length>80)errors.name='Enter a name of 2–80 characters.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(details.email||''))errors.email='Enter a valid email format.';if(!/^\d{10}$/.test(details.phone||''))errors.phone='Enter a ten-digit phone number.';if(!details.address||details.address.trim().length<10||details.address.length>200)errors.address='Enter an address of 10–200 characters.';if(!/^\d{6}$/.test(details.pin||'')||!['560001','560038'].includes(details.pin))errors.pin='Use a supported demo PIN: 560001 or 560038.';if(referral&&referral.trim().toUpperCase()!=='KEDRYN-FORGE')errors.referral='Invalid demo referral code. Remove or replace it.';return errors}
export async function placeMockOrder({details,referral='',idempotencyKey}){await wait(700);const existing=getState().orders.find(o=>o.idempotencyKey===idempotencyKey);if(existing)return ok({orderId:existing.id});const errors=validateCheckout(getState(),details,referral);if(Object.keys(errors).length)return fail('VALIDATION','Please correct the checkout fields.',errors);if(failCheckout){failCheckout=false;return fail('MOCK_PAYMENT','Simulated payment failed. Your cart and details are preserved.')}let orderId;save(s=>{const lines=s.cart.map(lineSnapshot),totals=cartTotals(s.cart),keys=[...new Set(s.cart.map(l=>`${l.deliveryDate}|${l.deliveryWindowId}`))];orderId=nextId(s,'order','KD-');const attrId=referral.trim()?`ATTR-${orderId}`:null;const order={id:orderId,customerAlias:'Asha Demo',createdAt:s.clock,lineSnapshots:lines,dispatchGroups:keys.map(key=>({key,date:key.split('|')[0],window:key.split('|')[1],status:'scheduled'})),totals,checkoutSnapshot:structuredClone(details),referralAttributionId:attrId,status:'scheduled',idempotencyKey};s.orders.push(order);if(attrId){s.attributions.push({id:attrId,orderId,gymId:'GYM01',normalizedCode:'KEDRYN-FORGE',source:'entered',attributedAt:s.clock});s.commissions.push({id:`COM-${orderId}`,orderId,gymId:'GYM01',eligibleRevenuePaise:totals.merchandise,rateBps:1000,commissionPaise:commissionFor(totals.merchandise),status:'pending'})}s.cart=[];s.checkout=structuredClone(details);s.referral=''});return ok({orderId})}
export async function advanceMockOrder(orderId,groupKey){await wait(200);const o=getState().orders.find(o=>o.id===orderId);if(!o||o.status==='cancelled'||o.seed)return fail('ORDER_STATE','This order cannot advance.');const g=o.dispatchGroups.find(g=>g.key===groupKey);const states=['scheduled','preparing','out for delivery','delivered'];if(!g||g.status==='delivered')return fail('GROUP_STATE','This delivery is already complete.');save(s=>{const order=s.orders.find(x=>x.id===orderId),group=order.dispatchGroups.find(x=>x.key===groupKey);group.status=states[states.indexOf(group.status)+1];order.status=order.dispatchGroups.every(x=>x.status==='delivered')?'delivered':order.dispatchGroups.some(x=>x.status==='out for delivery')?'out for delivery':'preparing';if(order.status==='delivered'){const c=s.commissions.find(x=>x.orderId===orderId);if(c)c.status='approved'}});return ok({status:getState().orders.find(x=>x.id===orderId).status})}
export async function cancelMockOrder(orderId){await wait(200);const o=getState().orders.find(o=>o.id===orderId);if(!o||o.seed||o.dispatchGroups.some(g=>g.status==='delivered')||o.status==='cancelled')return fail('CANCEL','This order cannot be cancelled.');save(s=>{const order=s.orders.find(x=>x.id===orderId);order.status='cancelled';order.dispatchGroups.forEach(g=>g.status='cancelled');const c=s.commissions.find(x=>x.orderId===orderId);if(c){c.status='void';c.eligibleRevenuePaise=0;c.commissionPaise=0}});return ok({orderId})}
export function loggedQuantity(lineId){return getState().logs.filter(e=>e.sourceOrderLineId===lineId).reduce((a,e)=>a+(e.consumedOrderQuantity||0),0)}
export async function logMeal(payload){await wait(150);const s=getState(),existing=s.logs.find(x=>x.idempotencyKey===payload.idempotencyKey);if(existing)return ok({entryId:existing.id});if(!/^2026-\d\d-\d\d$/.test(payload.diaryDate)||!['breakfast','lunch','snacks','dinner'].includes(payload.mealSlot)||!payload.foodItems?.length)return fail('LOG','Select a date, slot and valid food.');if(payload.foodItems.some(i=>!i.name||!Number.isFinite(+i.consumedAmount)||+i.consumedAmount<=0||!Number.isFinite(+i.baseAmount)||+i.baseAmount<=0||Object.values(i.baseNutrition).some(v=>!Number.isFinite(+v)||+v<0)))return fail('LOG_ITEM','Review food quantities and estimates.');if(payload.sourceOrderLineId){const line=s.orders.flatMap(o=>o.lineSnapshots).find(l=>l.id===payload.sourceOrderLineId);if(!line||loggedQuantity(line.id)+(payload.consumedOrderQuantity||0)>line.quantity+1e-8)return fail('OVER_LOGGED','This exceeds the unlogged purchased quantity.')}let entryId;save(s=>{entryId=nextId(s,'log','LOG-');s.logs.push({...payload,id:entryId,createdAt:s.clock,updatedAt:s.clock})});return ok({entryId})}
export async function updateFoodLog(id,foodItems,consumedOrderQuantity,diaryDate,mealSlot){await wait(100);const entry=getState().logs.find(x=>x.id===id);if(!entry)return fail('UNKNOWN_LOG','Food entry not found.');if(!/^2026-\d\d-\d\d$/.test(diaryDate)||!['breakfast','lunch','snacks','dinner'].includes(mealSlot))return fail('LOG_DATE','Choose a valid diary date and meal slot.');if(!foodItems?.length||foodItems.some(i=>!i.name||!Number.isFinite(+i.consumedAmount)||+i.consumedAmount<=0||!Number.isFinite(+i.baseAmount)||+i.baseAmount<=0||Object.values(i.baseNutrition).some(v=>!Number.isFinite(+v)||+v<0)))return fail('LOG_ITEM','Review food quantities and estimates.');if(entry.sourceOrderLineId){const line=getState().orders.flatMap(o=>o.lineSnapshots).find(l=>l.id===entry.sourceOrderLineId);const other=getState().logs.filter(e=>e.id!==id&&e.sourceOrderLineId===line.id).reduce((a,e)=>a+(e.consumedOrderQuantity||0),0);if(other+consumedOrderQuantity>line.quantity+1e-8)return fail('OVER_LOGGED','This exceeds the unlogged purchased quantity.')}save(s=>{const e=s.logs.find(x=>x.id===id);e.foodItems=foodItems;e.consumedOrderQuantity=consumedOrderQuantity||null;e.diaryDate=diaryDate;e.mealSlot=mealSlot;e.updatedAt=s.clock});return ok({entryId:id})}
export async function deleteFoodLog(id){await wait(100);if(!getState().logs.some(x=>x.id===id))return fail('UNKNOWN_LOG','Food entry not found.');save(s=>s.logs=s.logs.filter(x=>x.id!==id));return ok({id})}
export function entryNutrition(e){return addNutrition(e.foodItems.map(i=>Object.fromEntries(Object.entries(i.baseNutrition).map(([k,v])=>[k,v*(i.consumedAmount/i.baseAmount)]))))}
export function dailyNutrition(date){return addNutrition(getState().logs.filter(e=>e.diaryDate===date).map(entryNutrition))}
export async function analyzeSamplePhoto(id){await wait(900);const map={rajma:'M09',chilla:'M02',paneer:'M07'};const m=meals[map[id]];if(!m)return fail('SAMPLE','Unknown sample photo.');return ok({items:[{id:'PHOTO-1',name:m.name,sourceMealId:m.id,baseAmount:m.standardServingGrams,baseUnit:'g',baseNutrition:m.nutritionPerStandard,consumedAmount:m.standardServingGrams}],disclosure:'Bundled sample with a predetermined estimate.'})}
export async function analyzeUploadedPhoto(file){await wait(900);if(!['image/jpeg','image/png','image/webp'].includes(file.type))return fail('FILE_TYPE','Choose a JPEG, PNG or WebP image.');if(file.size>10*1024*1024)return fail('FILE_SIZE','Choose an image under 10MB.');return ok({items:[{id:'UPLOAD-1',name:'Sample food item',baseAmount:100,baseUnit:'g',baseNutrition:{kcal:200,p:8,c:25,f:7,fi:3},consumedAmount:100}],disclosure:'This demo does not recognize uploaded food. The items below are a sample breakdown—replace or edit them before confirming.'})}
export async function getPartnerMetrics({from='2026-09-26',to='2026-10-02'}={}){await wait(150);if(from>to)return fail('RANGE','Start date must be before end date.');const s=getState();const rows=s.commissions.map(c=>{const o=s.orders.find(x=>x.id===c.orderId);return {order_id:o.id,order_date_ist:o.createdAt.slice(0,10),customer_alias:o.customerAlias,order_status:o.status,merchandise_inr:o.totals.merchandise/100,discount_inr:0,eligible_inr:c.eligibleRevenuePaise/100,commission_rate_percent:c.rateBps/100,commission_inr:c.commissionPaise/100,commission_status:c.status}}).filter(r=>r.order_date_ist>=from&&r.order_date_ist<=to).sort((a,b)=>b.order_date_ist.localeCompare(a.order_date_ist)||a.order_id.localeCompare(b.order_id));const positive=rows.filter(r=>r.commission_status!=='void');const sum=(arr,key)=>arr.reduce((a,r)=>a+r[key],0);const balances={pending:sum(s.commissions.filter(c=>c.status==='pending'),'commissionPaise'),approved:sum(s.commissions.filter(c=>c.status==='approved'),'commissionPaise'),paid:sum(s.commissions.filter(c=>c.status==='paid'),'commissionPaise')};return ok({rows,metrics:{customers:new Set(positive.map(r=>r.customer_alias)).size,orders:positive.length,eligiblePaise:Math.round(sum(positive,'eligible_inr')*100),commissionPaise:Math.round(sum(positive,'commission_inr')*100)},balances})}
export function exportPartnerCsv(rows,from,to){const cols=['order_id','order_date_ist','customer_alias','order_status','merchandise_inr','discount_inr','eligible_inr','commission_rate_percent','commission_inr','commission_status'];const safe=v=>{let x=String(v??'');if(/^[=+\-@\t\r]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"'};const csv=[cols.join(','),...rows.map(r=>cols.map(c=>safe(r[c])).join(','))].join('\r\n');return {blob:new Blob([csv],{type:'text/csv;charset=utf-8'}),filename:`kedryn-referrals-${from}-to-${to}.csv`}}
export function resetDemo(confirmed){if(!confirmed)return fail('CONFIRM','Confirm reset first.');reset();return ok({reset:true})}
